[package]
org = "dell"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

#balleina dependencies must be defines as an array of tables, not a single object
[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.12.0"  

