[package]
org = "dell"
name = "backend"
version = "0.1.0"
distribution = "2201.12.7"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.3.1"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.5.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.12.0"

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.12.0"

